<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TrangPC" name="Default test" tests="1" failures="1" timestamp="18 May 2016 13:55:38 GMT" time="49.388" errors="0">
  <testcase name="test_region" time="38.443" classname="testRegion.TestRegion">
    <failure type="com.applitools.eyes.TestFailedException" message="&amp;apos;Region&amp;apos; of &amp;apos;Sachmem&amp;apos;. See details at https://eyes.applitools.com/app/sessions/251938721068513?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Region' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938721068513?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRegion.TestRegion.test_region(TestRegion.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_region -->
</testsuite> <!-- Default test -->
