<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="49388" started-at="2016-05-18T13:54:49Z" finished-at="2016-05-18T13:55:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="49388" started-at="2016-05-18T13:54:49Z" finished-at="2016-05-18T13:55:38Z">
      <class name="testRegion.TestRegion">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testRegion.TestRegion@17550481]" name="beforeTest" is-config="true" duration-ms="10907" started-at="2016-05-18T20:54:49Z" finished-at="2016-05-18T20:55:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="test_region()[pri:0, instance:testRegion.TestRegion@17550481]" name="test_region" duration-ms="38443" started-at="2016-05-18T20:55:00Z" finished-at="2016-05-18T20:55:38Z">
          <exception class="com.applitools.eyes.TestFailedException">
            <message>
              <![CDATA['Region' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938721068513?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.applitools.eyes.TestFailedException: 'Region' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938721068513?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRegion.TestRegion.test_region(TestRegion.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- com.applitools.eyes.TestFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_region -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testRegion.TestRegion@17550481]" name="afterTest" is-config="true" duration-ms="1" started-at="2016-05-18T20:55:38Z" finished-at="2016-05-18T20:55:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testRegion.TestRegion -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
