<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TrangPC" name="testRnM.RnMsbt" tests="33" failures="10" timestamp="17 May 2016 11:55:57 GMT" time="3938.129" errors="0">
  <testcase name="test_sachmem" time="48.723" classname="testRnM.RnMsbt">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Match 3,4 02&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251938815978706?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Match 3,4 02' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938815978706?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnM.RnMsbt.test_sachmem(RnMsbt.java:58)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="44.410" classname="testRnM.RnMsbt">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Match 3,4 02&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251938817084058?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Match 3,4 02' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938817084058?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnM.RnMsbt.test_sachmem(RnMsbt.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="136.365" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="138.881" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="130.363" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="51.944" classname="testRnM.RnMsbt">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Match 3,4 02&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251938816158850?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Match 3,4 02' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938816158850?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnM.RnMsbt.test_sachmem(RnMsbt.java:58)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="128.407" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="44.025" classname="testRnM.RnMsbt">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Match 3,4 02&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251938815546863?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Match 3,4 02' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938815546863?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnM.RnMsbt.test_sachmem(RnMsbt.java:58)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="129.958" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="129.559" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="128.025" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="49.278" classname="testRnM.RnMsbt">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Match 3,4 02&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251938816468630?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Match 3,4 02' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938816468630?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnM.RnMsbt.test_sachmem(RnMsbt.java:58)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="126.841" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="129.839" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="129.225" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="128.006" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="134.227" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="130.324" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="606.767" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="44.320" classname="testRnM.RnMsbt">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Match 3,4 02&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251938816512146?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Match 3,4 02' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938816512146?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnM.RnMsbt.test_sachmem(RnMsbt.java:58)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="132.408" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="130.055" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="129.378" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="45.926" classname="testRnM.RnMsbt">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Match 3,4 02&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251938817513767?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Match 3,4 02' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938817513767?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnM.RnMsbt.test_sachmem(RnMsbt.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="127.230" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="44.966" classname="testRnM.RnMsbt">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Match 3,4 02&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251938815502728?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Match 3,4 02' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938815502728?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnM.RnMsbt.test_sachmem(RnMsbt.java:58)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="134.036" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="129.535" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="129.429" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="43.616" classname="testRnM.RnMsbt">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Match 3,4 02&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251938815452196?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Match 3,4 02' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938815452196?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnM.RnMsbt.test_sachmem(RnMsbt.java:58)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="127.600" classname="testRnM.RnMsbt"/>
  <testcase name="test_sachmem" time="45.925" classname="testRnM.RnMsbt">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Match 3,4 02&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251938814665843?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Match 3,4 02' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251938814665843?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnM.RnMsbt.test_sachmem(RnMsbt.java:58)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="128.538" classname="testRnM.RnMsbt"/>
</testsuite> <!-- testRnM.RnMsbt -->
